### ISSUE TITLE
... error installing theme. No access to admin center. clean grav installation

### ISSUE THREAD

**Issue by sigmahlm** [Sommerregen/grav-theme-alpha#1]
Twig_Error_Runtime thrown with message "An exception has been thrown during the rendering of a template ("Array to string conversion") in "partials/themes-details.html.twig" at line 72."  Stacktrace: #21 Twig_Error_Runtime in /var/www/grav/vendor/twig/twig/lib/Twig/Template.php:396 #20 Whoops\Exception\ErrorException in /var/www/grav/cache/twig/c9/c97eaa9ed201b5ece361fd045ce641ab33ec8f1862e22676c973ac2a7dd7af44.php:213 #19 Whoops\Run:handleError in /var/www/grav/cache/twig/c9/c97eaa9ed201b5ece361fd045ce641ab33ec8f1862e22676c973ac2a7dd7af44.php:213 #18 __TwigTemplate_495ba16742a8decb3212ffc5f2187ee146979971e53870e751b1c19bdf0e4cbe:doDisplay in /var/www/grav/vendor/twig/twig/lib/Twig/Template.php:381 #17 Twig_Template:displayWithErrorHandling in /var/www/grav/vendor/twig/twig/lib/Twig/Template.php:355 #16 Twig_Template:display in /var/www/grav/cache/twig/db/dbcb986320e97266fbcc4a9fa00a8aad2b613fe90d1de7dbf00da7d7eaef6109.php:199 #15 __TwigTemplate_d25d7f3501a5bcea2dac2f2ea9cd1f06cdc1ce5deecfd96214d495eb3cf21a40:block_content in /var/www/grav/vendor/twig/twig/lib/Twig/Template.php:167 #14 Twig_Template:displayBlock in /var/www/grav/cache/twig/ee/ee39bd2bc749f723e3d404620d452ea4342c73ae3b154bf014ac51d7dbffe1e5.php:292 #13 __TwigTemplate_d62ab87916cfafa1d7997b313a218c1c64e79b3f319c7685bfbcb68f7db9143b:block_page in /var/www/grav/vendor/twig/twig/lib/Twig/Template.php:167 #12 Twig_Template:displayBlock in /var/www/grav/cache/twig/ee/ee39bd2bc749f723e3d404620d452ea4342c73ae3b154bf014ac51d7dbffe1e5.php:45 #11 __TwigTemplate_d62ab87916cfafa1d7997b313a218c1c64e79b3f319c7685bfbcb68f7db9143b:doDisplay in /var/www/grav/vendor/twig/twig/lib/Twig/Template.php:381 #10 Twig_Template:displayWithErrorHandling in /var/www/grav/vendor/twig/twig/lib/Twig/Template.php:355 #9 Twig_Template:display in /var/www/grav/cache/twig/db/dbcb986320e97266fbcc4a9fa00a8aad2b613fe90d1de7dbf00da7d7eaef6109.php:54 #8 __TwigTemplate_d25d7f3501a5bcea2dac2f2ea9cd1f06cdc1ce5deecfd96214d495eb3cf21a40:doDisplay in /var/www/grav/vendor/twig/twig/lib/Twig/Template.php:381 #7 Twig_Template:displayWithErrorHandling in /var/www/grav/vendor/twig/twig/lib/Twig/Template.php:355 #6 Twig_Template:display in /var/www/grav/vendor/twig/twig/lib/Twig/Template.php:366 #5 Twig_Template:render in /var/www/grav/vendor/twig/twig/lib/Twig/Environment.php:347 #4 Twig_Environment:render in /var/www/grav/system/src/Grav/Common/Twig/Twig.php:334 #3 Grav\Common\Twig\Twig:processSite in /var/www/grav/system/src/Grav/Common/Grav.php:186 #2 Grav\Common\Grav:Grav\Common{closure} in /var/www/grav/vendor/pimple/pimple/src/Pimple/Container.php:113 #1 Pimple\Container:offsetGet in /var/www/grav/system/src/Grav/Common/Grav.php:288 #0 Grav\Common\Grav:process in /var/www/grav/index.php:38

**Comment by Sommerregen** [comment]
I have seen this error before. This is because you are not using the latest Grav + Admin releases. Please update to **Grav 1.1.0-rc.3** and **Admin 1.1.0-rc.4**. I'll close this issue now. Feel free to open, when the issue persists.
